# Generated by Django 3.0.5 on 2020-05-14 10:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_auto_20200513_1426'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userplacetrade',
            options={'ordering': ['-price', 'createdOn'],
                     'verbose_name_plural': 'UserPlaceTrade'},
        ),
        migrations.AlterField(
            model_name='profile',
            name='age',
            field=models.IntegerField(blank=True, validators=[django.core.validators.MaxValueValidator(
                100), django.core.validators.MinValueValidator(1)], null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(blank=True, choices=[(
                'male', 'Male'), ('female', 'Female')], max_length=10),
        ),
        migrations.AlterField(
            model_name='userplacetrade',
            name='sale_type',
            field=models.CharField(choices=[('market_order', 'MARKET ORDER'), (
                'ask', 'ASK'), ('bid', 'BID')], default='market_order', max_length=100),
        ),
        migrations.AlterField(
            model_name='userplacetrade',
            name='status',
            field=models.CharField(choices=[('complete', 'COMPLETE'), ('pending', 'PENDING'), (
                'cancel', 'CANCEL'), ('failed', 'FAILED')], default=1, max_length=50),
        ),
    ]
