# Generated by Django 3.0.5 on 2020-05-14 10:41

import datetime
import django.core.validators
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0004_auto_20200514_1602'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='profile_pic',
        ),
        migrations.RemoveField(
            model_name='stockmanagement',
            name='available_quantity',
        ),
        migrations.AlterField(
            model_name='profile',
            name='age',
            field=models.IntegerField(blank=True, default=0, validators=[
                                      django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userplacetrade',
            name='status',
            field=models.CharField(choices=[('complete', 'COMPLETE'), ('pending', 'PENDING'), (
                'cancel', 'CANCEL'), ('failed', 'FAILED')], default='pending', max_length=50),
        ),
    ]
