# Generated by Django 3.0.5 on 2020-05-15 08:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0006_auto_20200514_2020'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradetransaction',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tradetransaction',
            name='trade_id',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='stock.UserPlaceTrade'),
        ),
        migrations.AlterField(
            model_name='userplacetrade',
            name='status',
            field=models.CharField(choices=[('complete', 'COMPLETE'), ('pending', 'PENDING'), ('cancel', 'CANCEL'), ('timeout', 'TIMEOUT')], default='pending', max_length=50),
        ),
    ]
