# Generated by Django 3.0.5 on 2020-05-15 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0007_auto_20200515_1425'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tradetransaction',
            old_name='trade_id',
            new_name='trade',
        ),
    ]
