# Generated by Django 3.0.5 on 2020-05-18 20:11

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0009_auto_20200516_0121'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradetransaction',
            name='transaction_on',
            field=models.DateTimeField(auto_now_add=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tradetransaction',
            name='trade',
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='stock.UserPlaceTrade'),
        ),
        migrations.AlterField(
            model_name='userplacetrade',
            name='action',
            field=models.CharField(choices=[(
                'buy', 'BUY'), ('sell', 'SELL'), ('company', 'Company(IPO)')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='userplacetrade',
            name='sale_type',
            field=models.CharField(choices=[('market_order', 'MARKET ORDER'), ('ask', 'ASK'), (
                'bid', 'BID'), ('ipo', 'IPO')], default='market_order', max_length=100),
        ),
    ]
